FinanceiroLirio/FinanceiroLirio.Web/Areas/Administrador/Controllers/CongregacaoController.cs
using FinanceiroLirio.Entidades;
using FinanceiroLirio.Regras;
using FinanceiroLirio.Web.Areas.Administrador.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinanceiroLirio.Web.Areas.Administrador.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class CongregacaoController : Controller
    {
        // GET: Administrador/Congregacao
        public ActionResult Nova()
        {
            try
            {
                CidadeBusiness cb = new CidadeBusiness();

                var model = new CadastroCongregacaoModel();

                model.Cidade = cb.ListaTodasCidadesDropdownlist();
                ViewBag.ListaItensEstados = cb.ListaTodasCidadesDropdownlist();
                ViewBag.Titulo = "Cadastrar congregação";
                return View(model);
            }
            catch (Exception e)
            {
                TempData["Mensagem"] = "Erro: " + e.Message;
                TempData["Resposta"] = "Falha";
                return RedirectToAction("Novo", "Home");
            }
        }

        [HttpPost]
        public ActionResult Nova(CadastroCongregacaoModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Congregacao c = new Congregacao();

                    c.Apelido = model.Apelido;
                    c.Descricao = model.Descricao;
                    Endereco e = new Endereco();

                    e.Rua = model.Rua;
                    e.Numero = model.Numero;
                    e.Cep = model.Cep;
                    e.Bairro = model.Bairro;
                    e.IdCidade = model.CidadeSelecionada;
                    e.Complemento = model.Complemento;

                    EnderecoBusiness eb = new EnderecoBusiness();

                    e = eb.NovoEndereco(e);
                    c.IdEndereco = e.IdEndereco;

                    CongregacaoBusiness cb = new CongregacaoBusiness();

                    c = cb.NovaCongregacao(c);

                    TempData["Mensagem"] = "Congregação cadastrada com sucesso.";
                    TempData["Resposta"] = "Sucesso";
                }
            }
            catch(Exception e)
            {
                TempData["Mensagem"] = "Erro: " + e.Message;
                TempData["Resposta"] = "Falha";
            }
             return RedirectToAction("Nova");
        }

        
        public ActionResult Lista()
        {
            List<ListaCongregacaoModel> lista = new List<ListaCongregacaoModel>();
            try
            {
                CongregacaoBusiness cb = new CongregacaoBusiness();
                List<Congregacao> c = cb.TodasCongregacoes();
                
                foreach (Congregacao o in c)
                {
                    ListaCongregacaoModel tmp = new ListaCongregacaoModel();
                    tmp.Apelido = o.Apelido;
                    tmp.Cidade = o.Endereco.Cidade.Nome;
                    tmp.Estado = o.Endereco.Cidade.Estado.Nome;
                    tmp.IdCongregacao = o.IdCongregacao;

                    lista.Add(tmp);
                    
                }
                return View(lista);
            }
            catch(Exception e)
            {
                TempData["Mensagem"] = "Erro: " + e.Message;
                TempData["Resposta"] = "Falha";
                return RedirectToAction("Novo", "Home");
            }
            
        }
        
    }
}

FinanceiroLirio/FinanceiroLirio.Web/Areas/Administrador/Views/Congregacao/Lista.cshtml
@model IEnumerable<FinanceiroLirio.Web.Areas.Administrador.Models.ListaCongregacaoModel>

@{
    ViewBag.Titulo = "Lista";
    Layout = "~/Views/Shared/_layout.cshtml";
}
<head>
    <style>
        .link {
             color:white;
        }        
    </style>
</head>

<h4 class="left-align">Lista de congregações</h4><hr />
<br />

<button class="btn waves-effect waves-light">
    @Html.ActionLink("Nova", "Nova", "Congregacao",new {@class="link"})
    <i class="material-icons right">add_circle</i>
</button>

<div class="card-panel grey lighten-5 z-depth-1">
    <table class="striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Apelido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cidade)
            </th>
            <th>Opções</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Apelido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cidade)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                </td>
            </tr>
        }

    </table>
</div>

FinanceiroLirio/FinanceiroLirio.Web/Areas/Administrador/Views/Congregacao/Nova.cshtml
@model FinanceiroLirio.Web.Areas.Administrador.Models.CadastroCongregacaoModel

@{
    ViewBag.Title = "Nova";
    Layout = "~/Views/Shared/_layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="row">
        <h5 class="left-align">Cadastro de congregação</h5>
        <hr>
        <br />
         
        @if (TempData["Mensagem"] != null)
            {
                if (TempData["Resposta"].ToString() == "Sucesso")
                {
                    <div class="row">
                        <div class="col s12 m6">
                            <div class="card green lighten-1">
                                <div class="card-content black-text">
                                    <span class="card-title">Mensagem</span>
                                    <p>
                                        @TempData["Mensagem"].ToString()
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                else if (TempData["Resposta"].ToString() == "Falha")
                {
                    <div class="row">
                        <div class="col s12 m6">
                            <div class="card red lighten-1">
                                <div class="card-content black-text">
                                    <span class="card-title">Mensagem</span>
                                    <p>
                                        @TempData["Mensagem"].ToString()
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="card-panel grey lighten-5 z-depth-1">
            <div class="row">
                @*<h5>Congregação</h5>*@
                <div class="input-field col s5">
                    @Html.EditorFor(model => model.Descricao)
                    @Html.LabelFor(model => model.Descricao)
                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                </div>
                <div class="input-field col s4">
                    @Html.EditorFor(model => model.Apelido)
                    @Html.LabelFor(model => model.Apelido)
                    @Html.ValidationMessageFor(model => model.Apelido, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                @*<h5>Endereço</h5>*@
                <div class="input-field col s4">
                    @Html.EditorFor(model => model.Rua)
                    @Html.LabelFor(model => model.Rua)
                    @Html.ValidationMessageFor(model => model.Rua, "", new { @class = "text-danger" })
                </div>
                <div class="input-field col s2">
                    @Html.EditorFor(model => model.Numero)
                    @Html.LabelFor(model => model.Numero)
                    @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                </div>
                <div class="input-field col s3">
                    @Html.EditorFor(model => model.Complemento)
                    @Html.LabelFor(model => model.Complemento)
                    @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="input-field col s2">
                    @Html.EditorFor(model => model.Cep)
                    @Html.LabelFor(model => model.Cep)
                    @Html.ValidationMessageFor(model => model.Cep, "", new { @class = "text-danger" })
                </div>
                <div class="input-field col s3">
                    @Html.EditorFor(model => model.Bairro)
                    @Html.LabelFor(model => model.Bairro)
                    @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <div class="input-field col s4">
                    @Html.DropDownListFor(model => model.CidadeSelecionada, Model.Cidade, "Value", "Text")

                    @Html.LabelFor(model => model.CidadeSelecionada)
                    @Html.ValidationMessageFor(model => model.CidadeSelecionada, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s2">
                <button class="btn waves-effect waves-light" type="submit" name="action">
                    Salvar
                    <i class="material-icons right">send</i>
                </button>
            </div>
            <div class="input-field col s2">
                <a href="/Administrador/Home/Index" style="background-color:#e53935;color:white;width:150px;" class="waves-effect waves-light btn">
                    Cancelar <i class="material-icons right">clear</i>
                </a>
            </div>
        </div>
    </div>
}